branches:
  only:
  - master
language: python
python:
- 2.7
install:
- pip install -r requirements.txt
notifications:
  email:
    on_success: always
    on_failure: always
before_install:
  - git submodule foreach git pull origin master   
script:
- make html  
